// src/components/images/image.svelte
<script lang="ts">
  let {
    src,
    alt = '',
    caption,
    width,
    height,
    class: className = '',
  }: {
    src: string;
    alt?: string;
    caption?: string;
    width?: number;
    height?: number;
    class?: string;
  } = $props();
</script>

<figure class="my-6 flex flex-col gap-2{className ? ' ' + className : ''}">
  <img
    {src}
    {alt}
    {width}
    {height}
    loading="lazy"
    decoding="async"
    class="block h-auto max-w-3xl rounded-md"
  />

  {#if caption}
    <figcaption class="text-sm text-neutral-400">{caption}</figcaption>
  {/if}
</figure>

// react-app/src/components/Sanity/ImageComponent.tsx
import React from 'react';
import { getImageDimensions } from '@sanity/asset-utils';
import { urlFor } from '../../client';

export const ImageComponent = ({ value }: any) => {
  const { width, height } = getImageDimensions(value);
  return (
    <div className="contentBody__imageWrapper">
      <img 
        src={urlFor(value).width(800).fit('max').auto('format').url()}
        alt={value.alt || ' '}
        loading="lazy"
        style={{
          aspectRatio: (width / height).toFixed(2),
        }}
      />
    </div>
  );
};
